// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC13suop8dxSTNyn9cYWyLHoI7ButEo0Z0',
    appId: '1:858453853807:web:bdb46b6cc9bff9e8932f9a',
    messagingSenderId: '858453853807',
    projectId: 'safespotcm',
    authDomain: 'safespotcm.firebaseapp.com',
    storageBucket: 'safespotcm.firebasestorage.app',
    measurementId: 'G-7C6B52D6D6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd3nkOkPsrNlbhkRtti71bzGKzsKfbx2U',
    appId: '1:858453853807:android:96bd4368e10b01c2932f9a',
    messagingSenderId: '858453853807',
    projectId: 'safespotcm',
    storageBucket: 'safespotcm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_Zr5cQfvKNVN0QgSTaH94JqmJjsqeNJI',
    appId: '1:858453853807:ios:44bd160e645be842932f9a',
    messagingSenderId: '858453853807',
    projectId: 'safespotcm',
    storageBucket: 'safespotcm.firebasestorage.app',
    iosBundleId: 'com.example.safespot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_Zr5cQfvKNVN0QgSTaH94JqmJjsqeNJI',
    appId: '1:858453853807:ios:44bd160e645be842932f9a',
    messagingSenderId: '858453853807',
    projectId: 'safespotcm',
    storageBucket: 'safespotcm.firebasestorage.app',
    iosBundleId: 'com.example.safespot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC13suop8dxSTNyn9cYWyLHoI7ButEo0Z0',
    appId: '1:858453853807:web:62c20888c3e766ee932f9a',
    messagingSenderId: '858453853807',
    projectId: 'safespotcm',
    authDomain: 'safespotcm.firebaseapp.com',
    storageBucket: 'safespotcm.firebasestorage.app',
    measurementId: 'G-SFWHD3LF83',
  );
}
